// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.5.0.0
//      Runtime Version:4.0.30319.235
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
namespace ISIS.Web.Areas.Schedule.UITests.Instructor
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.5.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Instructors page")]
    public partial class InstructorsPageFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "InstructorsPage.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Instructors page", "In order to maintain a list of instructors\nAs a department chair\nI want to naviga" +
                    "te the links of the instructor page", GenerationTargetLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Instructors page")]
        [NUnit.Framework.CategoryAttribute("selenium")]
        public virtual void InstructorsPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Instructors page", new string[] {
                        "selenium"});
#line 7
this.ScenarioSetup(scenarioInfo);
#line 8
 testRunner.When("I navigate to ~/Schedule/Instructor");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Text",
                        "Url"});
            table1.AddRow(new string[] {
                        "ISIS",
                        "/"});
            table1.AddRow(new string[] {
                        "Course Scheduling",
                        "/Schedule"});
            table1.AddRow(new string[] {
                        "Instructors",
                        ""});
#line 9
 testRunner.Then("the page has breadcrumbs as follows", ((string)(null)), table1);
#line 14
 testRunner.And("the page has a list of instructors");
#line 15
 testRunner.And("the page has a hint \"Choose an instructor from the left\"");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Follow breadcrumbs to the ISIS home page")]
        [NUnit.Framework.CategoryAttribute("selenium")]
        public virtual void FollowBreadcrumbsToTheISISHomePage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Follow breadcrumbs to the ISIS home page", new string[] {
                        "selenium"});
#line 18
this.ScenarioSetup(scenarioInfo);
#line 19
 testRunner.Given("I navigate to ~/Schedule/Instructor");
#line 20
 testRunner.When("I click ISIS");
#line 21
 testRunner.Then("I navigate to ~/");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Follow breadcrumbs to the scheduling area")]
        [NUnit.Framework.CategoryAttribute("selenium")]
        public virtual void FollowBreadcrumbsToTheSchedulingArea()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Follow breadcrumbs to the scheduling area", new string[] {
                        "selenium"});
#line 24
this.ScenarioSetup(scenarioInfo);
#line 25
 testRunner.Given("I navigate to ~/Schedule/Instructor");
#line 26
 testRunner.When("I click Course Scheduling");
#line 27
 testRunner.Then("I navigate to ~/Schedule");
#line hidden
            testRunner.CollectScenarioErrors();
        }
    }
}
#endregion
