// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.5.0.0
//      Runtime Version:4.0.30319.225
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
namespace ISIS.Domain.Tests
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.5.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Course Title")]
    public partial class CourseTitleFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "CourseTitle.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Course Title", "As a scheduler\nI want to set the course title", GenerationTargetLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Rename the course")]
        [NUnit.Framework.CategoryAttribute("domain")]
        public virtual void RenameTheCourse()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Rename the course", new string[] {
                        "domain"});
#line 6
this.ScenarioSetup(scenarioInfo);
#line 7
 testRunner.Given("I have created a new course BIOL 1301");
#line 8
 testRunner.When("I rename the course to \"New Title\"");
#line 9
 testRunner.Then("the course is renamed to \"New Title\"");
#line 10
 testRunner.And("it does nothing else");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Rename the course with short title")]
        [NUnit.Framework.CategoryAttribute("domain")]
        public virtual void RenameTheCourseWithShortTitle()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Rename the course with short title", new string[] {
                        "domain"});
#line 13
this.ScenarioSetup(scenarioInfo);
#line 14
 testRunner.Given("I have created a new course BIOL 1301");
#line 15
 testRunner.When("I rename the course to \"Very Very Very Long New Title\" with short title \"Short ne" +
                    "w title\"");
#line 16
 testRunner.Then("the course is renamed to \"Very Very Very Long New Title\" with short title \"Short " +
                    "new title\"");
#line 17
 testRunner.And("it does nothing else");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Rename the course to a different title")]
        [NUnit.Framework.CategoryAttribute("domain")]
        public virtual void RenameTheCourseToADifferentTitle()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Rename the course to a different title", new string[] {
                        "domain"});
#line 20
this.ScenarioSetup(scenarioInfo);
#line 21
 testRunner.Given("I have created a new course BIOL 1301");
#line 22
 testRunner.And("I have renamed the course to \"Introductory Biology\"");
#line 23
 testRunner.When("I rename the course to \"New Title\"");
#line 24
 testRunner.Then("the course is renamed from \"Introductory Biology\" to \"New Title\"");
#line 25
 testRunner.And("it does nothing else");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Rename the course to a different title with short title")]
        [NUnit.Framework.CategoryAttribute("domain")]
        public virtual void RenameTheCourseToADifferentTitleWithShortTitle()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Rename the course to a different title with short title", new string[] {
                        "domain"});
#line 28
this.ScenarioSetup(scenarioInfo);
#line 29
 testRunner.Given("I have created a new course BIOL 1301");
#line 30
 testRunner.And("I have renamed the course to \"Introductory Biology\" with short title \"Intro to Bi" +
                    "ology\"");
#line 31
 testRunner.When("I rename the course to \"Very Very Very Long New Title\" with short title \"Short ne" +
                    "w title\"");
#line 32
 testRunner.Then("the course is renamed from \"Introductory Biology\" with short title \"Intro to Biol" +
                    "ogy\" to \"Very Very Very Long New Title\" with short title \"Short new title\"");
#line 33
 testRunner.And("it does nothing else");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Rename the course to the same")]
        [NUnit.Framework.CategoryAttribute("domain")]
        public virtual void RenameTheCourseToTheSame()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Rename the course to the same", new string[] {
                        "domain"});
#line 36
this.ScenarioSetup(scenarioInfo);
#line 37
 testRunner.Given("I have created a new course BIOL 1301");
#line 38
 testRunner.And("I have renamed the course to \"Introductory Biology\"");
#line 39
 testRunner.When("I rename the course to \"Introductory Biology\"");
#line 40
 testRunner.Then("it does nothing");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Change only the short title")]
        [NUnit.Framework.CategoryAttribute("domain")]
        public virtual void ChangeOnlyTheShortTitle()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Change only the short title", new string[] {
                        "domain"});
#line 43
this.ScenarioSetup(scenarioInfo);
#line 44
 testRunner.Given("I have created a new course BIOL 1301");
#line 45
 testRunner.And("I have renamed the course to \"Introductory Biology\" with short title \"Intro to Bi" +
                    "ology\"");
#line 46
 testRunner.When("I rename the course to \"Introductory Biology\" with short title \"Short new title\"");
#line 47
 testRunner.Then("the course is renamed from \"Introductory Biology\" with short title \"Intro to Biol" +
                    "ogy\" to \"Introductory Biology\" with short title \"Short new title\"");
#line 48
 testRunner.And("it does nothing else");
#line hidden
            testRunner.CollectScenarioErrors();
        }
    }
}
#endregion
