// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.5.0.0
//      Runtime Version:4.0.30319.225
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
namespace ISIS.Domain.Tests
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.5.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Course Status")]
    public partial class CourseStatusFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "CourseStatus.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Course Status", "As a scheduler\nI want to manage the status of courses", GenerationTargetLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Activate a course")]
        [NUnit.Framework.CategoryAttribute("domain")]
        public virtual void ActivateACourse()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Activate a course", new string[] {
                        "domain"});
#line 6
this.ScenarioSetup(scenarioInfo);
#line 7
 testRunner.Given("I have created a course");
#line 8
 testRunner.And("I have set the course CIP to 12.3456");
#line 9
 testRunner.And("I have set the course description to \"Description goes here\"");
#line 10
 testRunner.When("I activate the course");
#line 11
 testRunner.Then("the course is activated");
#line 12
 testRunner.And("it does nothing else");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Can\'t activate a course without a CIP")]
        [NUnit.Framework.CategoryAttribute("domain")]
        public virtual void CanTActivateACourseWithoutACIP()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Can\'t activate a course without a CIP", new string[] {
                        "domain"});
#line 15
this.ScenarioSetup(scenarioInfo);
#line 16
 testRunner.Given("I have created a course");
#line 17
 testRunner.And("I have set the course description to \"Description goes here\"");
#line 18
 testRunner.When("I activate the course");
#line 19
 testRunner.Then("the aggregate state is invalid");
#line 20
 testRunner.And("the message is \"Your attempt to activate the course failed because the course is " +
                    "missing a CIP.\"");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Can\'t activate a course without a description")]
        [NUnit.Framework.CategoryAttribute("domain")]
        public virtual void CanTActivateACourseWithoutADescription()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Can\'t activate a course without a description", new string[] {
                        "domain"});
#line 23
this.ScenarioSetup(scenarioInfo);
#line 24
 testRunner.Given("I have created a course");
#line 25
 testRunner.And("I have set the course CIP to 12.3456");
#line 26
 testRunner.When("I activate the course");
#line 27
 testRunner.Then("the aggregate state is invalid");
#line 28
 testRunner.And("the message is \"Your attempt to activate the course failed because the course is " +
                    "missing a description.\"");
#line hidden
            testRunner.CollectScenarioErrors();
        }
    }
}
#endregion
