// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.5.0.0
//      Runtime Version:4.0.30319.225
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
namespace ISIS.Schedule
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.5.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Course Equipment")]
    public partial class CourseEquipmentFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "CourseEquipment.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Course Equipment", "As a department chair\nI want to track the equipment required to properly teach a " +
                    "course", GenerationTargetLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Add required instructor equipment for course")]
        [NUnit.Framework.CategoryAttribute("domain")]
        public virtual void AddRequiredInstructorEquipmentForCourse()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add required instructor equipment for course", new string[] {
                        "domain"});
#line 6
this.ScenarioSetup(scenarioInfo);
#line 7
 testRunner.Given("I have set up a course");
#line 8
 testRunner.When("I require 1 \"whiteboard\" for the course");
#line 9
 testRunner.Then("1 \"whiteboard\" is required for the course, for a total of 1");
#line 10
 testRunner.And("it does nothing else");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Add required student equipment for course")]
        [NUnit.Framework.CategoryAttribute("domain")]
        public virtual void AddRequiredStudentEquipmentForCourse()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add required student equipment for course", new string[] {
                        "domain"});
#line 13
this.ScenarioSetup(scenarioInfo);
#line 14
 testRunner.Given("I have set up a course");
#line 15
 testRunner.When("I require 1 \"PC\" per student for the course");
#line 16
 testRunner.Then("1 \"PC\" per student is required for the course");
#line 17
 testRunner.And("it does nothing else");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Add required shared student equipment for course")]
        [NUnit.Framework.CategoryAttribute("domain")]
        public virtual void AddRequiredSharedStudentEquipmentForCourse()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add required shared student equipment for course", new string[] {
                        "domain"});
#line 20
this.ScenarioSetup(scenarioInfo);
#line 21
 testRunner.Given("I have set up a course");
#line 22
 testRunner.When("I require 1 \"lab sink\" per 2 students for the course");
#line 23
 testRunner.Then("1 \"lab sink\" per 2 students is required for the course");
#line 24
 testRunner.And("it does nothing else");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Remove required instructor equipment for course")]
        [NUnit.Framework.CategoryAttribute("domain")]
        public virtual void RemoveRequiredInstructorEquipmentForCourse()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Remove required instructor equipment for course", new string[] {
                        "domain"});
#line 27
this.ScenarioSetup(scenarioInfo);
#line 28
 testRunner.Given("I have set up a course");
#line 29
 testRunner.And("I require 1 \"whiteboard\" for the course");
#line 30
 testRunner.When("I no longer require 1 \"whiteboard\" for the course");
#line 31
 testRunner.Then("1 \"whiteboard\" is no longer required for the course, for a total of 0");
#line 32
 testRunner.And("it does nothing else");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Remove required student equipment for course")]
        [NUnit.Framework.CategoryAttribute("domain")]
        public virtual void RemoveRequiredStudentEquipmentForCourse()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Remove required student equipment for course", new string[] {
                        "domain"});
#line 35
this.ScenarioSetup(scenarioInfo);
#line 36
 testRunner.Given("I have set up a course");
#line 37
 testRunner.And("I require 1 \"PC\" per student for the course");
#line 38
 testRunner.When("I no longer require 1 \"PC\" per student for the course");
#line 39
 testRunner.Then("1 \"PC\" per student is no longer required for the course");
#line 40
 testRunner.And("it does nothing else");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Remove required shared student equipment for course")]
        [NUnit.Framework.CategoryAttribute("domain")]
        public virtual void RemoveRequiredSharedStudentEquipmentForCourse()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Remove required shared student equipment for course", new string[] {
                        "domain"});
#line 43
this.ScenarioSetup(scenarioInfo);
#line 44
 testRunner.Given("I have set up a course");
#line 45
 testRunner.And("I require 1 \"lab sink\" per 2 students for the course");
#line 46
 testRunner.When("I no longer require 1 \"lab sink\" per 2 students for the course");
#line 47
 testRunner.Then("1 \"lab sink\" per 2 students is no longer required for the course");
#line 48
 testRunner.And("it does nothing else");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Add additional student equipment")]
        [NUnit.Framework.CategoryAttribute("domain")]
        public virtual void AddAdditionalStudentEquipment()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add additional student equipment", new string[] {
                        "domain"});
#line 51
this.ScenarioSetup(scenarioInfo);
#line 52
 testRunner.Given("I have set up a course");
#line 53
 testRunner.And("I require 1 \"PC\" per 2 students for the course");
#line 54
 testRunner.When("I require 1 \"PC\" per student for the course");
#line 55
 testRunner.Then("1 \"PC\" per student is required for the course");
#line 56
 testRunner.And("it does nothing else");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Add additional instructor equipment")]
        [NUnit.Framework.CategoryAttribute("domain")]
        public virtual void AddAdditionalInstructorEquipment()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add additional instructor equipment", new string[] {
                        "domain"});
#line 59
this.ScenarioSetup(scenarioInfo);
#line 60
 testRunner.Given("I have set up a course");
#line 61
 testRunner.And("I require 1 \"PC\" for the course");
#line 62
 testRunner.When("I require 2 \"PC\" for the course");
#line 63
 testRunner.Then("2 \"PC\" is required for the course, for a total of 3");
#line 64
 testRunner.And("it does nothing else");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Instructor equipment doesnt affect student equipment")]
        [NUnit.Framework.CategoryAttribute("domain")]
        public virtual void InstructorEquipmentDoesntAffectStudentEquipment()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Instructor equipment doesnt affect student equipment", new string[] {
                        "domain"});
#line 67
this.ScenarioSetup(scenarioInfo);
#line 68
 testRunner.Given("I have set up a course");
#line 69
 testRunner.And("I require 1 \"PC\" per student for the course");
#line 70
 testRunner.When("I require 1 \"PC\" for the course");
#line 71
 testRunner.Then("1 \"PC\" is required for the course, for a total of 1");
#line 72
 testRunner.And("it does nothing else");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Over-remove student equipment")]
        [NUnit.Framework.CategoryAttribute("domain")]
        public virtual void Over_RemoveStudentEquipment()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Over-remove student equipment", new string[] {
                        "domain"});
#line 75
this.ScenarioSetup(scenarioInfo);
#line 76
 testRunner.Given("I have set up a course");
#line 77
 testRunner.When("I no longer require 1 \"PC\" per student for the course");
#line 78
 testRunner.Then("the aggregate state is invalid");
#line 79
 testRunner.And("the message is \"Your attempt to remove this equipment requirement failed. The cou" +
                    "rse already doesn\'t require this equipment.\"");
#line hidden
            testRunner.CollectScenarioErrors();
        }
    }
}
#endregion
