// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.5.0.0
//      Runtime Version:4.0.30319.225
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
namespace ISIS.Schedule
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.5.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Template Term")]
    public partial class TemplateTermFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "TemplateTerm.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Template Term", "As a scheduler\nI want to assign terms to templates", GenerationTargetLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Assign a credit term to a credit template")]
        [NUnit.Framework.CategoryAttribute("domain")]
        public virtual void AssignACreditTermToACreditTemplate()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Assign a credit term to a credit template", new string[] {
                        "domain"});
#line 6
this.ScenarioSetup(scenarioInfo);
#line 7
 testRunner.Given("I have set up a course and template");
#line 8
 testRunner.And("I have created a term");
#line 9
 testRunner.When("I assign the term to the template");
#line 10
 testRunner.Then("the term is assigned to the template");
#line 11
 testRunner.And("the template\'s start and end dates match the term");
#line 12
 testRunner.And("it does nothing else");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Assign a CE term to a CE template")]
        [NUnit.Framework.CategoryAttribute("domain")]
        public virtual void AssignACETermToACETemplate()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Assign a CE term to a CE template", new string[] {
                        "domain"});
#line 15
this.ScenarioSetup(scenarioInfo);
#line 16
 testRunner.Given("I have set up a CE course and template");
#line 17
 testRunner.And("I have created a CE term");
#line 18
 testRunner.When("I assign the term to the template");
#line 19
 testRunner.Then("the term is assigned to the template");
#line 20
 testRunner.And("the template\'s start and end dates are blank");
#line 21
 testRunner.And("it does nothing else");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Cant assign a CE term to a credit template")]
        [NUnit.Framework.CategoryAttribute("domain")]
        public virtual void CantAssignACETermToACreditTemplate()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Cant assign a CE term to a credit template", new string[] {
                        "domain"});
#line 24
this.ScenarioSetup(scenarioInfo);
#line 25
 testRunner.Given("I have created a course and template");
#line 26
 testRunner.And("I have created a CE term");
#line 27
 testRunner.When("I assign the term to the template");
#line 28
 testRunner.Then("the aggregate state is invalid");
#line 29
 testRunner.And("the message is \"Your attempt to assign the term failed. The term is for continuin" +
                    "g education only.\"");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Cant assign a credit term to a CE template")]
        [NUnit.Framework.CategoryAttribute("domain")]
        public virtual void CantAssignACreditTermToACETemplate()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Cant assign a credit term to a CE template", new string[] {
                        "domain"});
#line 32
this.ScenarioSetup(scenarioInfo);
#line 33
 testRunner.Given("I have created a CE course and template");
#line 34
 testRunner.And("I have created a term");
#line 35
 testRunner.When("I assign the term to the template");
#line 36
 testRunner.Then("the aggregate state is invalid");
#line 37
 testRunner.And("the message is \"Your attempt to assign the term failed. The term is not for conti" +
                    "nuing education.\"");
#line hidden
            testRunner.CollectScenarioErrors();
        }
    }
}
#endregion
