// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.5.0.0
//      Runtime Version:4.0.30319.225
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
namespace ISIS.Schedule
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.5.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Template Copy")]
    public partial class TemplateCopyFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "TemplateCopy.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Template Copy", "In order to reduce data entry errors\nAs a scheduler\nI want to copy templates", GenerationTargetLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Copy a template")]
        [NUnit.Framework.CategoryAttribute("domain")]
        public virtual void CopyATemplate()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Copy a template", new string[] {
                        "domain"});
#line 7
this.ScenarioSetup(scenarioInfo);
#line 8
 testRunner.Given("I have set up a course");
#line 9
 testRunner.And("I have set up a term");
#line 10
 testRunner.And("I have created a template \"Source Template\"");
#line 11
 testRunner.And("I have assigned the term to the template");
#line 12
 testRunner.And("I have activated the template");
#line 13
 testRunner.And("I have created a new instructor");
#line 14
 testRunner.And("I have assigned the course to the instructor");
#line 15
 testRunner.And("I have assigned the instructor to the template");
#line 16
 testRunner.When("I copy the template \"Source Template\" to \"New Template\"");
#line 17
 testRunner.Then("the template is created");
#line 18
 testRunner.And("the template label is \"New Template\"");
#line 19
 testRunner.And("the template data matches the course data");
#line 20
 testRunner.And("the term is assigned to the template");
#line 21
 testRunner.And("the template\'s start and end dates match the term");
#line 22
 testRunner.And("the template is activated");
#line 23
 testRunner.And("the \"Source Template\" template is copied to \"New Template\"");
#line 24
 testRunner.And("the instructor is assigned to the template");
#line 25
 testRunner.And("it does nothing else");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Cant copy an obsolete template")]
        [NUnit.Framework.CategoryAttribute("domain")]
        public virtual void CantCopyAnObsoleteTemplate()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Cant copy an obsolete template", new string[] {
                        "domain"});
#line 28
this.ScenarioSetup(scenarioInfo);
#line 29
 testRunner.Given("I have set up a course");
#line 30
 testRunner.And("I have set up a term");
#line 31
 testRunner.And("I have created a template \"Source Template\"");
#line 32
 testRunner.And("I have assigned the term to the template");
#line 33
 testRunner.And("I have made the template obsolete");
#line 34
 testRunner.When("I copy the template \"Source Template\" to \"New Template\"");
#line 35
 testRunner.Then("the aggregate state is invalid");
#line 36
 testRunner.And("the message is \"Your attempt to copy the template failed. The source template is " +
                    "obsolete.\"");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Instructor equipment is copied with the template")]
        [NUnit.Framework.CategoryAttribute("domain")]
        public virtual void InstructorEquipmentIsCopiedWithTheTemplate()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Instructor equipment is copied with the template", new string[] {
                        "domain"});
#line 39
this.ScenarioSetup(scenarioInfo);
#line 40
 testRunner.Given("I have set up a course and template and activated the template");
#line 41
 testRunner.And("I require 1 \"PC\" for the template");
#line 42
 testRunner.When("I copy the template");
#line 43
 testRunner.Then("1 \"PC\" is required for the template, for a total of 1");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Student equipment is copied with the template")]
        [NUnit.Framework.CategoryAttribute("domain")]
        public virtual void StudentEquipmentIsCopiedWithTheTemplate()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Student equipment is copied with the template", new string[] {
                        "domain"});
#line 46
this.ScenarioSetup(scenarioInfo);
#line 47
 testRunner.Given("I have set up a course and template and activated the template");
#line 48
 testRunner.And("I require 1 \"PC\" per student for the template");
#line 49
 testRunner.When("I copy the template");
#line 50
 testRunner.Then("1 \"PC\" per student is required for the template");
#line hidden
            testRunner.CollectScenarioErrors();
        }
    }
}
#endregion
