// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.5.0.0
//      Runtime Version:4.0.30319.225
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
namespace ISIS.Schedule
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.5.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Term Setup")]
    public partial class TermSetupFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "TermSetup.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Term Setup", "As a scheduler\nI want to set up new terms", GenerationTargetLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Create a credit term")]
        [NUnit.Framework.CategoryAttribute("domain")]
        public virtual void CreateACreditTerm()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Create a credit term", new string[] {
                        "domain"});
#line 6
this.ScenarioSetup(scenarioInfo);
#line 7
 testRunner.When("I create a term 211FA \"2011 Fall 16-week\" from 9/1/2011 to 12/1/2011");
#line 8
 testRunner.Then("the term is created");
#line 9
 testRunner.And("the term abbreviation is 211FA");
#line 10
 testRunner.And("the term name is \"2011 Fall 16-week\"");
#line 11
 testRunner.And("the term start date is 9/1/2011");
#line 12
 testRunner.And("the term end date is 12/1/2011");
#line 13
 testRunner.And("the term is not for continuing education");
#line 14
 testRunner.And("it does nothing else");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Create a CE term")]
        [NUnit.Framework.CategoryAttribute("domain")]
        public virtual void CreateACETerm()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Create a CE term", new string[] {
                        "domain"});
#line 17
this.ScenarioSetup(scenarioInfo);
#line 18
 testRunner.When("I create a CE term CE211Q1 \"2011 Quarter 1\" from 9/1/2011 to 12/1/2011");
#line 19
 testRunner.Then("the term is created");
#line 20
 testRunner.And("the term abbreviation is CE211Q1");
#line 21
 testRunner.And("the term name is \"2011 Quarter 1\"");
#line 22
 testRunner.And("the term start date is 9/1/2011");
#line 23
 testRunner.And("the term end date is 12/1/2011");
#line 24
 testRunner.And("the term is for continuing education");
#line 25
 testRunner.And("it does nothing else");
#line hidden
            testRunner.CollectScenarioErrors();
        }
    }
}
#endregion
