// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.7.0.0
//      SpecFlow Generator Version:1.7.0.0
//      Runtime Version:4.0.30319.235
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
namespace ISIS.Web.Areas.Schedule.UITests
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.7.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("In order to navigate the application\nAs a user\nI want to navigate to the differen" +
        "t areas of the application")]
    public partial class ISISHomePageFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "ISISHomePage.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "ISIS Home Page", "In order to navigate the application\nAs a user\nI want to navigate to the differen" +
                    "t areas of the application", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("ISIS home page")]
        [NUnit.Framework.CategoryAttribute("selenium")]
        public virtual void ISISHomePage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("ISIS home page", new string[] {
                        "selenium"});
#line 7
this.ScenarioSetup(scenarioInfo);
#line 8
 testRunner.When("I navigate to the ISIS home page");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Text",
                        "Url"});
            table1.AddRow(new string[] {
                        "ISIS",
                        "http://localhost:1481/"});
            table1.AddRow(new string[] {
                        "Home",
                        ""});
#line 9
 testRunner.Then("the page has breadcrumbs as follows", ((string)(null)), table1);
#line 13
 testRunner.And("the page has a link to Course Scheduling");
#line 14
 testRunner.And("the page has a link to Facilities");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Link to scheduling")]
        [NUnit.Framework.CategoryAttribute("selenium")]
        public virtual void LinkToScheduling()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Link to scheduling", new string[] {
                        "selenium"});
#line 17
this.ScenarioSetup(scenarioInfo);
#line 18
 testRunner.Given("I have navigated to the ISIS home page");
#line 19
 testRunner.When("I click Course Scheduling");
#line 20
 testRunner.Then("I navigate to the Scheduling area");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Link to facilities")]
        [NUnit.Framework.CategoryAttribute("selenium")]
        public virtual void LinkToFacilities()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Link to facilities", new string[] {
                        "selenium"});
#line 23
this.ScenarioSetup(scenarioInfo);
#line 24
 testRunner.Given("I have navigated to the ISIS home page");
#line 25
 testRunner.When("I click Facilities");
#line 26
 testRunner.Then("I navigate to the Facilities area");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Link to ISIS home page")]
        [NUnit.Framework.CategoryAttribute("selenium")]
        public virtual void LinkToISISHomePage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Link to ISIS home page", new string[] {
                        "selenium"});
#line 29
this.ScenarioSetup(scenarioInfo);
#line 30
 testRunner.Given("I have navigated to the ISIS home page");
#line 31
 testRunner.When("I click ISIS");
#line 32
 testRunner.Then("I navigate to the ISIS home page");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#endregion
