// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.5.0.0
//      Runtime Version:4.0.30319.235
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
namespace ISIS.Web.Areas.Schedule.UITests
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.5.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Scheduling Home Page")]
    public partial class SchedulingHomePageFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "SchedulingHomePage.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Scheduling Home Page", "In order to use the scheduling system\nAs a user\nI want to navigate to different a" +
                    "reas of the scheduling system", GenerationTargetLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Scheduling home page")]
        [NUnit.Framework.CategoryAttribute("selenium")]
        public virtual void SchedulingHomePage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Scheduling home page", new string[] {
                        "selenium"});
#line 7
this.ScenarioSetup(scenarioInfo);
#line 8
 testRunner.When("I navigate to the scheduling area");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Text",
                        "Url"});
            table1.AddRow(new string[] {
                        "ISIS",
                        "/"});
            table1.AddRow(new string[] {
                        "Course Scheduling",
                        "/Schedule"});
            table1.AddRow(new string[] {
                        "Home",
                        ""});
#line 9
 testRunner.Then("the page has breadcrumbs as follows", ((string)(null)), table1);
#line 14
 testRunner.And("the page has a link to Instructors");
#line 15
 testRunner.And("the page has a link to Templates");
#line 16
 testRunner.And("the page has a link to Sections");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Follow breadcrumbs to the ISIS home page")]
        [NUnit.Framework.CategoryAttribute("selenium")]
        public virtual void FollowBreadcrumbsToTheISISHomePage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Follow breadcrumbs to the ISIS home page", new string[] {
                        "selenium"});
#line 19
this.ScenarioSetup(scenarioInfo);
#line 20
 testRunner.Given("I navigate to the scheduling area");
#line 21
 testRunner.When("I click ISIS");
#line 22
 testRunner.Then("I navigate to ~/");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Follow breadcrumbs to the scheduling area")]
        [NUnit.Framework.CategoryAttribute("selenium")]
        public virtual void FollowBreadcrumbsToTheSchedulingArea()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Follow breadcrumbs to the scheduling area", new string[] {
                        "selenium"});
#line 25
this.ScenarioSetup(scenarioInfo);
#line 26
 testRunner.Given("I navigate to the scheduling area");
#line 27
 testRunner.When("I click Course Scheduling");
#line 28
 testRunner.Then("I navigate to ~/Schedule");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Go to instructors page")]
        [NUnit.Framework.CategoryAttribute("selenium")]
        public virtual void GoToInstructorsPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Go to instructors page", new string[] {
                        "selenium"});
#line 32
this.ScenarioSetup(scenarioInfo);
#line 33
 testRunner.Given("I navigate to the scheduling area");
#line 34
 testRunner.When("I click Instructors");
#line 35
 testRunner.Then("I navigate to ~/Schedule/Instructor");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Go to templates page")]
        [NUnit.Framework.CategoryAttribute("selenium")]
        public virtual void GoToTemplatesPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Go to templates page", new string[] {
                        "selenium"});
#line 38
this.ScenarioSetup(scenarioInfo);
#line 39
 testRunner.Given("I navigate to the scheduling area");
#line 40
 testRunner.When("I click Templates");
#line 41
 testRunner.Then("I navigate to ~/Schedule/Template");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Go to sections page")]
        [NUnit.Framework.CategoryAttribute("selenium")]
        public virtual void GoToSectionsPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Go to sections page", new string[] {
                        "selenium"});
#line 44
this.ScenarioSetup(scenarioInfo);
#line 45
 testRunner.Given("I navigate to the scheduling area");
#line 46
 testRunner.When("I click Sections");
#line 47
 testRunner.Then("I navigate to ~/Schedule/Section");
#line hidden
            testRunner.CollectScenarioErrors();
        }
    }
}
#endregion
